name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          # PHP 8.2 - Laravel 11 only (Laravel 12 requires PHP 8.3+)
          - php: 8.2
            laravel: 11.*
            testbench: 9.*
            stability: prefer-lowest
          - php: 8.2
            laravel: 11.*
            testbench: 9.*
            stability: prefer-stable
          
          # PHP 8.3 - Both Laravel versions
          - php: 8.3
            laravel: 11.*
            testbench: 9.*
            stability: prefer-lowest
          - php: 8.3
            laravel: 11.*
            testbench: 9.*
            stability: prefer-stable
          - php: 8.3
            laravel: 12.*
            testbench: 10.*
            stability: prefer-lowest
          - php: 8.3
            laravel: 12.*
            testbench: 10.*
            stability: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.php == '8.3' && matrix.laravel == '12.*' && matrix.stability == 'prefer-stable'
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
